catalog/urls.py
from django.urls import path
from catalog import views


urlpatterns = [
    # Handling the index or main page
    path('', views.index, name='index'),
    # the books page
    path('books/', views.BookListView.as_view(), name='books'),
    # the books detail page
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

    # Handling the Author view
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    # the detailed view of author
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),

    # Viewing page based on current user
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),

    # Viewing page based on books borrowed to librarians only
    path('borrowed/', views.LoanedBooksByUserListViewForLibrarian.as_view(), name='all-borrowed'),

]
urlpatterns += [
    # renew the books by librarian
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]


urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    # path('', RedirectView.as_view(url='/catalog/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse  #used to generate URLS by reversing the URL patterns
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date

# creating models
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g Thermodynamics)')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the books natural Language (e.g English, French etc.)')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)

    # foreign key used because book can have only one author, but authors can have multiple books
    # Author as string rather than object because it has not yet defined
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter brief description of book')
    isbn = models.CharField('ISBN', max_length=13,  help_text='13 Chracter <a href="www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books and book can cover may genresself.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        # create a string for the Genre. This is required to display genre in Admin
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    id = models.UUIDField(primary_key = True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    # adding borrower
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book Availability'
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    """ adding new function to model for adding permissions """
    permissions = (("can_mark_returned", "set book as returned"),)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

import datetime

from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewBookForm


def index(request):
    # View function for home page of site

    # Generate counts of some of main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The all() is applied automatically
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }

    # Render the HTML template index.html with data in conxtext variable
    return render(request, 'catalog/index.html', context=context)

# class view for books
class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

# detail view of book
class BookDetailView(generic.DetailView):
    model = Book

# class view of Author
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksByUserListViewForLibrarian(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    """
    Generic class-based view listing books on loan to current user visible to librarian only
    """
    model = BookInstance
    template_name = 'catalog/student_books_list_borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.all().filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        book_renewal_form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if book_renewal_form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = book_renewal_form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        book_renewal_form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': book_renewal_form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Author


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class BookCreate(CreateView):
    model = Book
    fields = '__all__'


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{ author.last_name }}</h1>

  <small>{{ author.date_of_birth }}</small>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <hr>
        <p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></p>
        <p><strong>Summary:</strong> {{book.summary}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html

{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1 class="theme-color pt-4">Author's</h1>
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <tr>
                <th>Author</th>
            </tr>
            {% if author_list %}
                {% for author in author_list %}
                <tr>
                    <td>
                        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a>&nbsp; {{ author.last_name }}
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>There are no Authors yet.</td>
                </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 p-0">
        {% block sidebar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="nav flex-sm-column flex-row">
                  <li class="nav-item">
                      <img class="logo py-3" src="{% static 'catalog/img/logo.png' %}" alt="Logo" style="width: 120px;">
                  </li>
                  <li class="nav-item btn btn-warning btn-block">
                      <a class="nav-link" href="{% url 'index' %}">Home</a>
                  </li>
                  <li class="nav-item btn btn-warning btn-block">
                      <a class="nav-link" href="{% url 'books' %}">All books</a>
                  </li>
                  <li class="nav-item btn btn-warning btn-block">
                      <a class="nav-link" href="{% url 'authors' %}">All authors</a>
                  </li>
                  {% if user.is_authenticated %}
                      <li class="py-2">User: </li>
                       <li class="nav-item pb-2 text-primary"> <strong>{{ user.get_username }}</strong></li>
                      <li class="nav-item btn btn-warning btn-block">
                          <a class="nav-link" href="{% url 'my-borrowed' %}">My Borrowed</a>
                      </li>
                      <li class="nav-item btn btn-warning btn-block">
                          <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
                      </li>
                      {% if user.is_staff %}
                          <hr>
                          <li>Staff</li>
                          {% if perms.catalog.can_mark_returned %}
                                <!-- We can mark a BookInstance as returned. -->
                                <!-- Perhaps add code to link to a "book return" view here. -->
                              <li class="nav-item btn btn-warning btn-block">
                                  <a class="nav-link" href="{% url 'all-borrowed' %}">Borrowed</a>
                              </li>
                          {% endif %}
                      {% endif %}
                  {% else %}
                      <li class="nav-item btn btn-warning btn-block">
                          <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a>
                      </li>
                  {% endif %}
                </div>
            </div>
        </nav>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}
           {% block pagination %}
              {% if is_paginated %}
                <div class="pagination">
                  <span class="page-links">
                    {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                      <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
                    </span>
                    {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                  </span>
                </div>
              {% endif %}
           {% endblock %}
      </div>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1 class="theme-color pt-4">Book List</h1>
    <div class="table-responsive">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Title</th>
                <th>Author</th>
            </tr>
            {% if book_list %}
                {% for book in book_list %}
                <tr>
                    <td>
                        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    </td>
                    <td>{{ book.author }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>There are no available books in the library.</td>
                </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block title %} <title>My Local Library</title> {% endblock %}

{% block content %}
    <div class="jumbotron">
         <h1 class="theme-color">Local Library Home</h1>
      <p>Welcome to LocalLibrary, a webapp developed by <em class="text-success">mahmoodhussain.in!</em></p>
      <h2>Contents</h2>
      <p>The library has the following record counts:</p>
      <ul class="list-group">
        <li class="list-group-item"><strong>Books:</strong> {{ num_books }}</li>
        <li class="list-group-item"><strong>Copies:</strong> {{ num_instances }}</li>
        <li class="list-group-item"><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li class="list-group-item"><strong>Authors:</strong> {{ num_authors }}</li>
      </ul>
        <small>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</small>
    </div>

{% endblock %}

catalog/templates/catalog/student_books_list_borrowed.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}